### ISSUE TITLE
WEBRAT

### ISSUE THREAD

**Issue by ProfKambing** [Vaimok/webhack-0.8-and-0.9-crack#1]
WEBHOOK

**Comment by Crybaby6** [comment]
yea, it send s prestige ur ign and pc name when u run it

**Comment by M3gaPixel** [comment]
Anyway to get rid of that connection aswell with IGN and PC name?

**Comment by Crybaby6** [comment]
> Anyway to get rid of that connection aswell with IGN and PC name?

i mean just run the client with wireshark open get the webhook and nuke it

**Comment by M3gaPixel** [comment]
Ok thx

**Comment by 2bored2talk** [comment]
webhack is shit. fuck zprestige + 19xp.

**Comment by ProfKambing** [comment]
2noname2talk, i love zprestige

**Comment by ZenovJB** [comment]
> webhack is shit. fuck zprestige + 19xp. 
> 
> also, yea i had 0.4. luckily it was just a token logger not a backdoor. 
> 
> lamo fuck 19xp. 

LOL GO OUT

**Comment by RealzPrestige** [comment]
> webhack is shit. fuck zprestige + 19xp.
> 
> also, yea i had 0.4. luckily it was just a token logger not a backdoor.
> 
> lamo fuck 19xp.

HAHAH BREO I CANT 

oh yea vaimok the webhook was deleted by me 5 months ago :)

**Comment by Vaimok** [comment]
who tf asked.

**Comment by ProfKambing** [comment]
iq issue

**Comment by RealzPrestige** [comment]
> who tf asked.

Who Asked:
Who = Imaginary.
√-1 = Imaginary.
√-1 is also related to as i.
Who = i

**Comment by ProfKambing** [comment]
thats so deep, prestige.. thank you
